### PR TITLE
Adding dz.nc file to repo

### PR DESCRIPTION
**Pull request by michaelavs**

### CODE REVIEW

**Comment by michaelavs** [comment]
> Addition of the new file looks good, though a lot of entries in the registry seem to have changed. Do you have an idea what might have led to it?

I'm not sure, I ran `python create_registry` in the main directory (./geocat-datafiles) and thats what the output came out as. I am tempted to say it may be from a local branch issue. I created this branch from my "master" (which is also what I branch for the examples gallery repo) and cloned the datafiles repo into that branch. I'm going to probably have to remove this branch as is, so I'll check out what happens if I make a new branch and clone into there instead and run `python create_registry` again

**Comment by erogluorhan** [comment]
> I'm not sure, I ran `python create_registry` in the main directory (./geocat-datafiles) and thats what the output came out as. I am tempted to say it may be from a local branch issue. I created this branch from my "master" (which is also what I branch for the examples gallery repo) and cloned the datafiles repo into that branch. I'm going to probably have to remove this branch as is, so I'll check out what happens if I make a new branch and clone into there instead and run `python create_registry` again

The `registry.txt `in `master` branch has 328 entries. Yours should have 329 but it has 657; it seems it has exactly a doubled number of entries. When checked your `registry.txt`, there are redundant entries like:

`geocat-datafiles/folder_name/file_name`

whereas the proper entries should have a format of `folder_name/file_name`.

I would suggest before removing the local branch: Delete `regsitry.txt` in your local, regenerate it from scratch, see if it has only 329 entries in the proper format.

**Comment by michaelavs** [comment]
> > I'm not sure, I ran `python create_registry` in the main directory (./geocat-datafiles) and thats what the output came out as. I am tempted to say it may be from a local branch issue. I created this branch from my "master" (which is also what I branch for the examples gallery repo) and cloned the datafiles repo into that branch. I'm going to probably have to remove this branch as is, so I'll check out what happens if I make a new branch and clone into there instead and run `python create_registry` again
> 
> The `registry.txt `in `master` branch has 328 entries. Yours should have 329 but it has 657; it seems it has exactly a doubled number of entries. When checked your `registry.txt`, there are redundant entries like:
> 
> `geocat-datafiles/folder_name/file_name`
> 
> whereas the proper entries should have a format of `folder_name/file_name`.
> 
> I would suggest before removing the local branch: Delete `regsitry.txt` in your local, regenerate it from scratch, see if it has only 329 entries in the proper format.

I just tried doing what you suggested, but I think it is still outputting the file with redundant entries as git status says the branch is up to date with origin/dz. There is, however, and untracked file that is `geocat-datafiles/` and because you mentioned the redundant entries had the geocat-datafiles directory, do you think this may be why it is doubling entries?

**Comment by erogluorhan** [comment]
> I just tried doing what you suggested, but I think it is still outputting the file with redundant entries as git status says the branch is up to date with origin/dz. There is, however, and untracked file that is `geocat-datafiles/` and because you mentioned the redundant entries had the geocat-datafiles directory, do you think this may be why it is doubling entries?

It sounds like the reason; worth trying it (remove and regenerate please)

**Comment by michaelavs** [comment]
Closing due to branch issue. Re-opened in PR #3

**Pull request closed without merging**
