### PR TITLE
Bumped version for new release

### PR DESCRIPTION
**Pull request by erogluorhan**
A simple version change for newer release

### CODE REVIEW

**Review by anissa111 — APPROVED** [review]

**Comment by erogluorhan** [comment]
May be the part "19.1" is more than actually needed. The following could be enough:

"2021.1.0" which would indicate the "0th version created in January 2021". Thoughts?

**Comment by anissa111** [comment]
I think that is also fine, but might look like a date if there were a ```2021.1.1``` or something similar

**Comment by erogluorhan** [comment]
> I think that is also fine, but might look like a date if there were a `2021.1.1` or something similar

This is correct, but I think we should be okay if we document it in repo-specific docs as well as Contributor's Guide. I am looking at other packages such as Dask, they use the same format:

"Year.Month.Build Number", for example Dask 2021.01.0 was released on January 15, 2021.

**Comment by anissa111** [comment]
> This is correct, but I think we should be okay if we document it in repo-specific docs as well as Contributor's Guide. I am looking at other packages such as Dask, they use the same format:
> 
> "Year.Month.Build Number", for example Dask 2021.01.0 was released on January 15, 2021.

Oh, yeah good point. I am totally fine with either option and agree that ```2021.01.0``` would be a lot cleaner and that either method would be preferable to the one we have now.

**Comment by erogluorhan** [comment]
> > This is correct, but I think we should be okay if we document it in repo-specific docs as well as Contributor's Guide. I am looking at other packages such as Dask, they use the same format:
> > "Year.Month.Build Number", for example Dask 2021.01.0 was released on January 15, 2021.
> 
> Oh, yeah good point. I am totally fine with either option and agree that `2021.01.0` would be a lot cleaner and that either method would be preferable to the one we have now.
> 
> Also should there be any correlation to major/minor releases?

Whenever we have our major release (e.g. roadmap 1.0), maybe we can do such a versioning 1.0 / 202y.m.b. Check Dask changelogs, it looks like they were keeping a reference to both major versioning and above year.month.etc. format, as well as they seem to have had a recent change to their versioning, too :)

https://github.com/NCAR/geocat-datafiles/pull/14#issuecomment-763252531

I did not have a chance to read their docs in detail though

**Pull request merged**
